add docs
SkywalkingTest/skywalking-agent-testcases pull request #10
Opened 2018-02-09 10:14 UTC by ascrutae

2018-02-09 13:45 UTC, wu-sheng requested changes
需增加文档组织结构，描述顺序，调整用于准确定，以及补充部分重要内容。

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +用例工程是一个独立的Maven工程。该工程能够将用例打包成镜像。并且提供一个外部能够访问的Web服务
用例工程是一个独立的Maven工程，该工程会被打包成镜像。要求对外提供一个web服务，用于测试调用链追踪。

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +| testcase.yml       | 用来定义用例的基本信息，例如测试框架，用例覆盖版本的信息 |
删除`用来`。

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +| testcase.yml       | 用来定义用例的基本信息，例如测试框架，用例覆盖版本的信息 |
`定义用例的基本信息，例如测试框架，用例覆盖版本的信息` -> `定义用例的基本信息，如：框架名称、版本号`

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> ++------------------------------------------+
该图没有准确反映用例情况，推荐使用“时序图”，要描述此用例是自调用关系（实际发生了两次HTTP调用）

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +对pom.xml的一些建议，这样方便支持多版本测试，而不用修改任何代码
`对pom.xml的一些建议，这样方便支持多版本测试，而不用修改任何代码` -> `pom.xml建议：` 。文档描述过于口语化。

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +2. 建议将镜像的版本号设置成一个属性，并且把镜像的版本号属性的值设置成框架版本号属性
移除`建议`

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +2. 建议将镜像的版本号设置成一个属性，并且把镜像的版本号属性的值设置成框架版本号属性
`建议将镜像的版本号设置成一个属性，并且把镜像的版本号属性的值设置成框架版本号属性` -> `使用框架版本号作为镜像的版本号`

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +HttpClient测试用例中的pom.xml将httpclient的版本号设置成`${test.framework.version}`,镜像版本号设置成`${docker.image.version}`属性。具体请参考[配置](https://github.com/SkywalkingTest/skywalking-agent-testcases/blob/master/httpclient-
此处描述不清晰，应说明：将`docker.image.version`和`test.framework.version`定义成相同的值。

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +对pom.xml的一些建议，这样方便支持多版本测试，而不用修改任何代码
更倾向使用“最佳实践”或者“推荐”，而不仅仅是“建议”

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +在docker插件中有三个配置项需要注意：`imageName`, `imageTags`,`dockerDirectory`.
“以下三个字段应重点注意：”，其他说明移除，重复。

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +- 访问容器暴露的web服务，确保用例能够正常运行
从编写Dockerfile到运行docker-compose up之间，没有发现任何打镜像的操作，比如使用mvn插件的，是否遗漏？

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +1. Dockerfile添加探针挂载目录
如何添加？

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +3. docker-compose.xml 添加 mock-collector 镜像. 具体请参考[配置](https://github.com/SkywalkingTest/skywalking-agent-testcases/blob/master/httpclient-4.3.x-scenario/config/docker-compose.yml#L19-31)
应简单说明mock-collector用途。

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +5. 在docker-compose.xml中添加Agent的挂载. 具体参考[配置](https://github.com/SkywalkingTest/skywalking-agent-testcases/blob/master/httpclient-4.3.x-scenario/config/docker-compose.yml#L13-14)
整个流程完成后，应该如何验证编写正确？应提供相应的本地验证手段。

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +HttpClient期望数据文件 --- [expectedData.yaml](https://github.com/SkywalkingTest/skywalking-agent-testcases/blob/master/httpclient-4.3.x-scenario/config/expectedData.yaml)
应首先解释数据文件的组成部分，以及含义。示例只能作为参考。

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +**注意**: 期望文件中Segment的Span是后进先出的顺序
**注意**: 期望文件中Segment的Span是按照Span的结束顺序进行排列。不一定是`后进先出`，因为可能不是线性压栈。

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +以下是HttpClient的注册项的demo:
demo -> 示例  。中文文档不要使用不必要的英文。

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +
应在示例开始前，描述你支持的操作符。

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +以下对各个校验字段的描述:
应先描述文件结构（图），字段名，然后在示例。

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +以下对各个校验字段的描述:
应先描述文件结构（图），字段名，然后在示例。

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +根据HttpClient用例的运行流程，可以推测出用例生成两个Segment. 第一个Segment是访问CaseServlet所产生的, 暂且叫它`SegmentA`。第二Segment是CaseServlet通过HttpClient调用ContextPropagateServlet所产生的, 暂且叫它`SegmentB`. SegmentB中包含一个SegmentRef，并且SegmentR
这里不应直接描述HttpClient，而应该先描述Segment逻辑。

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +根据HttpClient用例的运行流程，可以推测出用例生成两个Segment. 第一个Segment是访问CaseServlet所产生的, 暂且叫它`SegmentA`。第二Segment是CaseServlet通过HttpClient调用ContextPropagateServlet所产生的, 暂且叫它`SegmentB`. SegmentB中包含一个SegmentRef，并且SegmentR
然后描述httpclient用例，根据Segement原理生成的对应关系。

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +| startTime     | Span开始时间.
时间格式，精度

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +| peer          | 访问的远端IP. 目前只有Exit类型的Span, 这个值不为空
`访问的远端IP. 目前只有Exit类型的Span, 这个值不为空` -> `访问的远端IP. Exit类型的Span, 这个值非空`。

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +| entryServiceName           | 调用链入口的Segment的服务名词. 例如HttpClient的entryServiceName为`/httpclient-case/case/httpclient`
程序中是实际上对应span的operationName，应明确说明对应关系

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +以下对各个校验字段的描述:
应先描述文件结构（图），字段名，然后在示例。

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +以下对各个校验字段的描述:
应先描述文件结构（图），字段名，然后在示例。

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +以下对各个字段的描述:
应先描述文件结构（图），字段名，然后在示例。

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +| -b agent_repository_branch | Skywalking Agent的工程的分支名. 默认为`master` |
没有Skywalking Agent的工程。请使用准确名称。

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +| -r agent_repository_url | Skywalking Agent的工程的URL. 默认为`https://github.com/apache/incubator-skywalking.git`|
没有Skywalking Agent的工程。

2018-02-09 13:45 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +测试用例运行完成之后，会自动生成报告，报告生成路径:
最终运行的输出文件目录结构，日志位置等信息缺失。这些对于调试用例错误十分重要。

2018-02-10 04:43 UTC, ascrutae commented on docs/how-to-write-a-plugin-testcase-cn.md
> +1. Dockerfile添加探针挂载目录
Done!

2018-02-10 04:47 UTC, ascrutae commented on docs/how-to-write-a-plugin-testcase-cn.md
> +| entryServiceName           | 调用链入口的Segment的服务名词. 例如HttpClient的entryServiceName为`/httpclient-case/case/httpclient`
Done!

2018-02-10 04:47 UTC, ascrutae commented on docs/how-to-write-a-plugin-testcase-cn.md
> +以下对各个字段的描述:
Done!

2018-02-10 04:48 UTC, ascrutae commented on docs/how-to-write-a-plugin-testcase-cn.md
> +5. 在docker-compose.xml中添加Agent的挂载. 具体参考[配置](https://github.com/SkywalkingTest/skywalking-agent-testcases/blob/master/httpclient-4.3.x-scenario/config/docker-compose.yml#L13-14)
目前校验只能通过文中最后提到的测试步骤进行测试。

2018-02-10 12:23 UTC, wu-sheng requested changes
文档结构依然需要调整，大量示例依然在格式描述之前。并请通过格式预览，确定markdown格式正确。

2018-02-10 12:23 UTC, wu-sheng commented on docs/.#how-to-write-a-plugin-testcase-cn.md
> +xin@ascrutae.90596
Why have this file?

2018-02-10 12:23 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +HttpClient用例运行在Tomcat容器中，该用例包含两个Servlet: CaseServlet 和 ContextPropagateServlet，其中CaseServlet通过HttpClient调用ContextPropagateServlet.
应该把描述的，调用方式，如HttpClient、Web HTTP放到下图中，这样这段描述就没有必要了。并能强调发起了网络调用。

2018-02-10 12:23 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +5. 在docker-compose.xml中添加Agent的挂载. 具体参考[配置](https://github.com/SkywalkingTest/skywalking-agent-testcases/blob/master/httpclient-4.3.x-scenario/config/docker-compose.yml#L13-14)
@ascrutae 应该在这里说明，如何测试。比如增加到文尾的链接（注意，中文文档可能链接失效），或者说明

2018-02-10 12:23 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +``
格式错误，请注意查看预览。

2018-02-10 12:23 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +HttpClient测试用例中只有一个实例,
换行不正确，请注意查看预览

2018-02-10 12:23 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +2. 编写segmentItems
换行不正确，请注意查看预览

2018-02-10 12:23 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +在pom.xml中添加`profiles`配置节点。其中每一个`profile`就代表中`testcase.yaml`中support_versions列表中的一个, `profile`中的id命名格式为: `${project.dir_name}-${support_version}`.
换行不正确，请注意查看预览

2018-02-10 12:23 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +1. 添加testcase.yaml文件. HttpClient的[testcase.yaml](https://github.com/SkywalkingTest/skywalking-agent-testcases/blob/master/httpclient-4.3.x-scenario/testcase.yml)
为什么例子要放在同一行中？

2018-02-10 13:22 UTC, ascrutae commented on docs/how-to-write-a-plugin-testcase-cn.md
> +2. 编写segmentItems
Done!

2018-02-11 02:43 UTC, wu-sheng approved these changes

2018-02-11 02:43 UTC, wu-sheng commented on docs/how-to-write-a-plugin-testcase-cn.md
> +HttpClient测试用例的docker-compose.xml请参考[配置](https://github.com/SkywalkingTest/skywalking-agent-testcases/blob/master/httpclient-4.3.x-scenario/config/docker-compose.yml)
换行不正确

2018-02-11 02:43 UTC, merged