spring-with-qualified-op-name-scenario
SkywalkingTest/skywalking-agent-testcases pull request #55
Opened 2019-03-13 04:38 UTC by BFergerson

I'm running into an issue when trying to verify this. I'm getting:
```
start docker container
start docker container
Creating network "spring-with-qualified-op-name-scenario-spring-resttemplate-402_annotation-402_restannotation-500_default" with the default driver
Creating network "spring-with-qualified-op-name-scenario-spring-resttemplate-401_annotation-401_restannotation-501_default" with the default driver
Pulling spring-with-qualified-op-name-scenario (skywalking/spring-with-qualified-op-name-scenario:Spring-RestTemplate-4.0.2_Annotation-4.0.2_RestAnnotation-5.0.0)...
Pulling spring-with-qualified-op-name-scenario (skywalking/spring-with-qualified-op-name-scenario:Spring-RestTemplate-4.0.1_Annotation-4.0.1_RestAnnotation-5.0.1)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]ERROR: pull access denied for skywalking/spring-with-qualified-op-name-scenario, repository does not exist or may require 'docker login'
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]ERROR: pull access denied for skywalking/spring-with-qualified-op-name-scenario, repository does not exist or may require 'docker login'
3 containers are running, The validate program will be retried in 40 seconds.
http://localhost:18180/spring-with-qualified-op-name-scenario/qualifiedname/qualifiedname-case
http://localhost:18080/spring-with-qualified-op-name-scenario/qualifiedname/qualifiedname-case
```

I can't access the `http://localhost:18180/spring-with-qualified-op-name-scenario/qualifiedname/qualifiedname-case` url so I'm not able to make the correct `expectedData.yaml` file.

Any clue what I'm doing wrong?

2019-03-13 14:49 UTC, wu-sheng commented
@ascrutae Please verify the test case PR.

2019-03-16 06:28 UTC, ascrutae commented on spring-with-qualified-op-name-scenario/pom.xml
> +                        <imageTag>1.0.0</imageTag>
the version of imageTag should be `${docker.image.version}`

2019-03-16 22:05 UTC, BFergerson commented
@ascrutae, thank you. I've implemented the `expectedData.yml` file and even though when I do a diff on the expected vs actual data I'm getting the following validation issues:
```
[2019-03-16 15:55:12:556] [INFO] - org.skywalking.apm.test.agent.tool.validator.assertor.SegmentAssert.spansEquals(SegmentAssert.java:57) - span[test.apache.skywalking.testcase.qualifiedname.controller.SpringEndpointQualifiedNameController.acceptAllExplicit()] are not equal ignore this segment. 
tags: 
 expected: http://localhost:8080/spring-with-qualified-op-name-scenario/qualifiedname/acceptAllExplicit
 actual: http://localhost:8080/spring-with-qualified-op-name-scenario/qualifiedname/acceptAllImplicit
[2019-03-16 15:55:12:556] [INFO] - org.skywalking.apm.test.agent.tool.validator.assertor.SegmentAssert.spansEquals(SegmentAssert.java:50) - excepted span size is equals actual span size, begin to assert span.
[2019-03-16 15:55:12:556] [INFO] - org.skywalking.apm.test.agent.tool.validator.assertor.SegmentAssert.spansEquals(SegmentAssert.java:46) - excepted span size are not equals actual span size, ignore this segment.
[2019-03-16 15:55:12:556] [INFO] - org.skywalking.apm.test.agent.tool.validator.assertor.SegmentAssert.spansEquals(SegmentAssert.java:46) - excepted span size are not equals actual span size, ignore this segment.
[2019-03-16 15:55:12:557] [INFO] - org.skywalking.apm.test.agent.tool.validator.assertor.SegmentAssert.spansEquals(SegmentAssert.java:50) - excepted span size is equals actual span size, begin to assert span.
[2019-03-16 15:55:12:557] [INFO] - org.skywalking.apm.test.agent.tool.validator.assertor.SegmentRefAssert.findSegmentRef(SegmentRefAssert.java:36) - ref are not equal ignore this ref. 
parent segment id: 
 expected: 1.45.15527732252050000
 actual: 1.42.15527732250100000
[2019-03-16 15:55:12:557] [ERROR] - org.skywalking.apm.test.agent.tool.Main.main(Main.java:40) - assert failed.
segment refs: 
 expected count : 1
 actual: 0
```

When I do a diff on the expected vs actual the only differences are on fields:
 - segmentId
 - parentTraceSegmentId
 - startTime
 - endTime

I believe all of those are able to be different (+ parentTraceSgementId which is set dynamically). How does it think the tags are wrong if even in the actual data vs expected data it shows it to be correct?

2019-03-16 22:56 UTC, ascrutae commented on spring-with-qualified-op-name-scenario/config/expectedData.yaml
> +      - {key: "url", value: "http://localhost:18180/spring-with-qualified-op-name-scenario/qualifiedname/qualifiedname-case"}
```suggestion
      - {key: "url", value: "http://localhost:{SERVER_OUTPUT_PORT}/spring-with-qualified-op-name-scenario/qualifiedname/qualifiedname-case"}
```

2019-03-16 23:23 UTC, ascrutae submitted a review, later dismissed
LGTM

2019-03-16 23:24 UTC, BFergerson commented
@ascrutae, thanks again. Last issues. It's saying there is a validation error on the tags. Like so:
```
tags: 
 expected: http://localhost:8080/spring-with-qualified-op-name-scenario/qualifiedname/acceptAllExplicit
 actual: http://localhost:8080/spring-with-qualified-op-name-scenario/qualifiedname/acceptAllImplicit
```

Again, if I do a diff on the actual vs expected there is no difference besides the expected fields.

2019-03-16 23:31 UTC, ascrutae commented
The port is different from the port your export in `docker-compose.yml`, because of the autotest program runs multiple test cases at the same time, and the port need replace with the real port in run time.

2019-03-16 23:45 UTC, ascrutae commented
Because no one knows the report sequence of the trace segment, so the integration test needs to compare all segments in `expecatedData.yml,` that's is the warning message you saw. You should read all assert message if you want to know the real reason why the test case failed.

2019-03-17 15:08 UTC, wu-sheng requested changes
`test_framework` and `support-versions` names in `testcase.yml` need to be changed, based on case names. Also profile name in `pom.xml` need to match those.

2019-03-17 16:34 UTC, BFergerson commented
@wu-sheng, I wasn't sure what those values were supposed to be so I copied the `spring-scenario`. Instead of `Spring-RestTemplate_Annotation_RestAnnotation` what are you suggesting? I thought these values were what I needed to test multiple versions of Spring (as you initially suggested).

2019-03-17 16:46 UTC, wu-sheng commented
You could click the report links in your main repo pr. You will see those names. I am sorry, we don't make the meaning clear.

Case name shows as a group in test report, and versions just match version list in each group.

2019-03-17 16:47 UTC, wu-sheng commented
You will see, there are two comments by robot, our test robot. They look like same, but actually they are based on the two different cases, you provide in this pr.

2019-03-17 16:48 UTC, wu-sheng commented
Name js not quite important to be very accurate, but need to keep them clear and unique.

2019-03-17 16:58 UTC, BFergerson commented
@wu-sheng, sorry but I'm not sure what you're asking me to change it to. I have two test scenarios: `spring-with-qualified-op-name-scenario` and `spring-with-request-method-op-name-scenario`. I can modify the `test_framework` for both of them but I'm not sure what kind of values you're looking for. I'm still using Spring and the REST annotations. It seems to fit the scenarios I added. If it doesn't could you give me an example?

2019-03-18 00:42 UTC, wu-sheng commented
But you can see there are two test results
- https://github.com/apache/incubator-skywalking/pull/2353#issuecomment-473671686
- https://github.com/apache/incubator-skywalking/pull/2353#issuecomment-473672630

Each of them is for one of your case, but you can see, there looks like the same. The reason is the following two settings are same.
- [`test_framework`](https://github.com/BFergerson/agent-auto-integration-testcases/blob/master/spring-with-request-method-op-name-scenario/testcase.yml#L14)
- [`support_versions `](https://github.com/BFergerson/agent-auto-integration-testcases/blob/master/spring-with-qualified-op-name-scenario/testcase.yml#L22-L24)

This is the whole report for daily, https://github.com/SkyAPMTest/agent-integration-test-report. In order to make it clear to read, I suggest you use `SpringMVC` for both folder cases. And in version, we decribe the difference, such as `spring-4.0.1-with-qualified-op-name-scenario`, `spring-4.0.1-with-request-method-op-name-scenario`.

Then the tool could group these two cases(including 4 versions) together, like this, https://github.com/SkyAPMTest/agent-integration-test-report#Jedis

Does this make sense now?

@ascrutae I think your document is misguiding poeple, could you adjust it a little?

2019-03-18 02:53 UTC, ascrutae commented
ok, Got it , I will do it

2019-03-18 03:29 UTC, BFergerson commented
@wu-sheng, makes sense, thanks. Does everything look correct now?

2019-03-18 04:00 UTC, wu-sheng commented
LGTM  @ascrutae please verify and run the cases

2019-03-18 05:23 UTC, wu-sheng approved these changes

2019-03-18 05:28 UTC, ascrutae approved these changes

2019-03-18 05:48 UTC, merged